version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "-b /opt/irisapp/vcopy.sh"
    init: true
    restart: always
    ports: 
      - 51773
      - 52773
      - 53773
    environment:
      - ISC_DATA_DIRECTORY=/voldata/iconfig
    volumes:
      - ./:/voldata
